default_install_hook_types:
  - pre-commit
  - pre-push
default_language_version:
  python: python3.9.16
repos:
  - hooks:
      - id: check-added-large-files
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
  - hooks:
      - additional_dependencies:
          - types-aiofiles
          - types-pyOpenSSL
          - types-ujson
          - types-requests
          - pydantic
        id: mypy
        name: typecheck
    repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
  - hooks:
      - id: autoflake
        name: remove unused imports
    repo: https://github.com/PyCQA/autoflake
    rev: v2.1.1
  # - hooks:
  #   - id: isort
  #     name: sort imports
  #   repo: https://github.com/pycqa/isort
  #   rev: 5.12.0
  # - hooks:
  #   - id: black
  #     name: format
  #   repo: https://github.com/psf/black
  #   rev: 23.3.0
  - hooks:
      - id: commitizen
        stages:
          - commit-msg
    repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.1
